name: fakenews
recipe: drupal10
config:
  webroot: web
  php: '8.1'
services:
  appserver:
    type: php:8.1
    via: apache
  database:
    type: mysql:5.7
    creds:
      user: drupal10
      password: drupal10
      database: drupal10
