<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_page_attachments_alter().
 */
function thatsfakenews_page_attachments_alter(array &$attachments) {
  foreach ($attachments['#attached']['html_head'] as $key => $attachment) {
    if ($attachment[1] == 'system_meta_generator') {
      unset($attachments['#attached']['html_head'][$key]);
    }
  }
}

/**
 * Implements hook_form_alter().
 */
function thatsfakenews_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id !== 'views_exposed_form' && $form['#id'] !== 'views-exposed-form-news-news') {
    return;
  }

  // Convert the tag exposed form select to a select2 widget.
  $form['tags']['#type'] = 'select2';
}
